[package]
name = "gui"
version = "0.1.0"
authors = ["pvdbrand <peter@vdbrand.nl>"]
edition = "2018"

[dependencies]
rocket = "0.4.2"
rocket_contrib = "0.4.2"
serialport = "3.3.0"
serde = "1.0.*"
serde_derive = "1.0.*"